### ISSUE TITLE
windows下xampp部署后只有前台主页能打开 其他都是Object not found! 怎么回事？

### ISSUE THREAD

**Issue by tomhttp** [drodata/yii2-app-template#16]
windows下xampp部署后只有前台主页能打开 其他都是Object not found! 怎么回事？

**Comment by drodata** [comment]
你能贴出更详细的错误信息吗？我平时在 Debian 下开发，对 Windows 下的 xampp 环境不熟悉。你的 xampp 版本号是多少呢？我想在 Windows 下安装一下，看能否重现你的问题。

**Comment by tomhttp** [comment]
我把url管理那部分注释了 打开了 但是登录报错

An Error occurred while handling another error:
exception 'ReflectionException' with message 'Method common\models\User::updateLastLoginedAt() does not exist' in E:\xampp\htdocs\yii2-app-template\vendor\yiisoft\yii2\web\ErrorHandler.php:195
Stack trace:
#0 E:\xampp\htdocs\yii2-app-template\vendor\yiisoft\yii2\web\ErrorHandler.php(195): ReflectionMethod->__construct('common\\models\\U...', 'updateLastLogin...')
#1 E:\xampp\htdocs\yii2-app-template\vendor\yiisoft\yii2\views\errorHandler\callStackItem.php(26): yii\web\ErrorHandler->addTypeLinks('common\\models\\U...')
#2 E:\xampp\htdocs\yii2-app-template\vendor\yiisoft\yii2\base\View.php(330): require('E:\\xampp\\htdocs...')
#3 E:\xampp\htdocs\yii2-app-template\vendor\yiisoft\yii2\base\View.php(250): yii\base\View->renderPhpFile('E:\\xampp\\htdocs...', Array)
#4 E:\xampp\htdocs\yii2-app-template\vendor\yiisoft\yii2\web\ErrorHandler.php(249): yii\base\View->renderFile('@yii/views/erro...', Array, Object(yii\web\ErrorHandler))
#5 E:\xampp\htdocs\yii2-app-template\vendor\yiisoft\yii2\web\ErrorHandler.php(304): yii\web\ErrorHandler->renderFile('@yii/views/erro...', Array)
#6 E:\xampp\htdocs\yii2-app-template\vendor\yiisoft\yii2\web\ErrorHandler.php(326): yii\web\ErrorHandler->renderCallStackItem(NULL, NULL, 'common\\models\\U...', 'updateLastLogin...', Array, 3)
#7 E:\xampp\htdocs\yii2-app-template\vendor\yiisoft\yii2\views\errorHandler\exception.php(381): yii\web\ErrorHandler->renderCallStack(Object(yii\base\UnknownMethodException))
#8 E:\xampp\htdocs\yii2-app-template\vendor\yiisoft\yii2\base\View.php(330): require('E:\\xampp\\htdocs...')
#9 E:\xampp\htdocs\yii2-app-template\vendor\yiisoft\yii2\base\View.php(250): yii\base\View->renderPhpFile('E:\\xampp\\htdocs...', Array)
#10 E:\xampp\htdocs\yii2-app-template\vendor\yiisoft\yii2\web\ErrorHandler.php(249): yii\base\View->renderFile('@yii/views/erro...', Array, Object(yii\web\ErrorHandler))
#11 E:\xampp\htdocs\yii2-app-template\vendor\yiisoft\yii2\web\ErrorHandler.php(116): yii\web\ErrorHandler->renderFile('@yii/views/erro...', Array)
#12 E:\xampp\htdocs\yii2-app-template\vendor\yiisoft\yii2\base\ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\base\UnknownMethodException))
#13 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\base\UnknownMethodException))
#14 {main}
Previous exception:
exception 'yii\base\UnknownMethodException' with message 'Calling unknown method: common\models\User::updateLastLoginedAt()' in E:\xampp\htdocs\yii2-app-template\vendor\yiisoft\yii2\base\Component.php:290
Stack trace:
#0 [internal function]: yii\base\Component->__call('updateLastLogin...', Array)
#1 [internal function]: common\models\User->updateLastLoginedAt(Object(yii\base\Event))
#2 E:\xampp\htdocs\yii2-app-template\vendor\yiisoft\yii2\base\Component.php(545): call_user_func(Array, Object(yii\base\Event))
#3 E:\xampp\htdocs\yii2-app-template\common\models\LoginForm.php(62): yii\base\Component->trigger('after-login')
#4 E:\xampp\htdocs\yii2-app-template\frontend\controllers\SiteController.php(90): common\models\LoginForm->login()
#5 [internal function]: frontend\controllers\SiteController->actionLogin()
#6 E:\xampp\htdocs\yii2-app-template\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#7 E:\xampp\htdocs\yii2-app-template\vendor\yiisoft\yii2\base\Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#8 E:\xampp\htdocs\yii2-app-template\vendor\yiisoft\yii2\base\Module.php(523): yii\base\Controller->runAction('login', Array)
#9 E:\xampp\htdocs\yii2-app-template\vendor\yiisoft\yii2\web\Application.php(102): yii\base\Module->runAction('site/login', Array)
#10 E:\xampp\htdocs\yii2-app-template\vendor\yiisoft\yii2\base\Application.php(380): yii\web\Application->handleRequest(Object(yii\web\Request))
#11 E:\xampp\htdocs\yii2-app-template\frontend\web\index.php(18): yii\base\Application->run()
#12 {main}

**Comment by drodata** [comment]
> Method `common\models\User::updateLastLoginedAt()` does not exist

这个提示由一个已知的、尚未修改的错误造成的，一会儿我更新一下，你留意一下最新的 commit.

**Comment by tomhttp** [comment]
感谢 我再试试
